### ISSUE TITLE
Q: Difference between crossbeam-channel and multiqueue?

### ISSUE THREAD

**Issue by akurdyukov** [crossbeam-rs/crossbeam-channel#103]
Can you please help me understand the difference between crossbeam-channel and https://github.com/schets/multiqueue ?

**Comment by stjepang** [comment]
cc @schets

**Comment by stjepang** [comment]
Here are the most important differences:

* `multiqueue` is able to broadcast messages (i.e. a message is delivered to all receivers rather than just one).
* `multiqueue` supports futures.
* `crossbeam-channel` has `select!`.
* `crossbeam-channel` has unbounded and zero-capacity channels.

There are probably other differences, but I haven't used `multiqueue` that much so I don't know. My take on which one you should use is:

* If you need simple and easy channels to get you started, use `crossbeam-channel`. Consider it a successor to `std::sync::mpsc`.
* If you need broadcasting, use `multiqueue` (or the `bus` crate). Consider it a more advanced tool to reach out for when `std::sync::mpsc` and `crossbeam-channel` are not enough.

I don't have enough information to draw conclusions on differences in performance, though. But expect both to be very fast - their implementations are far from being naive. :)

**Comment by stjepang** [comment]
Closing the issue. If I can answer any other questions, don't hesitate to ask!
