### ISSUE TITLE
What's the license for examples/csp.rs?

### ISSUE THREAD

**Issue by erickt** [crossbeam-rs/crossbeam-channel#104]
Hello! We saw that the code in [examples/csp.rs](https://github.com/crossbeam-rs/crossbeam-channel/blob/master/examples/csp.rs) is derived from https://www.nada.kth.se/~snilsson/concurrency/#Match, but there doesn't appear to be a license associated with this example. Could one be added, or this file be removed, or at least exclude this file from the crate?

**Comment by stjepang** [comment]
The CSP example was published under Creative Commons Attribution 3.0 Unported License. I'll add attribution info. 

Can I ask you for an advice on two more licensing issues?

We have a [port of Go tests](https://github.com/crossbeam-rs/crossbeam-channel/blob/8b13b3a8ce861fd8dc3878bf3f5063979351f385/tests/golang.rs) in the `tests` directory, which should include a license notice too. Would adding a Go license to that file be enough? Alternatively, I could move those tests into a different repository so that crates depending on `crossbeam-channel` don't include that file at all.

We similarly have a [copy of `std::sync::mpsc` tests](https://github.com/crossbeam-rs/crossbeam-channel/blob/8b13b3a8ce861fd8dc3878bf3f5063979351f385/tests/mpsc.rs), where it might be a good idea to also add a Rust license. Do you think that is necessary?

**Comment by erickt** [comment]
Either way of these ways would work for us, but we can't give advice on which is the best approach you should take.

**Comment by erickt** [comment]
Thanks for this @stjepang! When do you expect to do another release? We're using cargo-vendor to incorporate crates into our repo, so we can't update our crossbeam-channel until it lands on crates.io.

**Comment by stjepang** [comment]
@erickt I'm preparing version 0.3.0 here: https://github.com/crossbeam-rs/crossbeam-channel/pull/106

I expect to release it this week, but if you need it sooner than that, I can bump the version now.

**Comment by erickt** [comment]
This week is fine, thanks @stjepang!

**Comment by ghost** [comment]
Version 0.3.0 has been released! You can see some comments on it [here](https://github.com/crossbeam-rs/crossbeam-channel/issues/61#issuecomment-435670389).
