### ISSUE TITLE
Add peek method on Receiver

### ISSUE THREAD

**Issue by droundy** [crossbeam-rs/crossbeam-channel#12]
I would be interested in having a "peek" method for Receiver, which would, if there is a message available allow a function to be called with a const reference to that message. This could allow a thread to do some work or thinking regarding a message before definitively removing it from the channel.

For instance, with a zero sized bounded channel, it could allow the sender to block until the message has been acted upon.

**Comment by stjepang** [comment]
I'm afraid this is impossible to implement on top of the current implementation. In order to borrow a message from the channel without receiving it, we would have to lock the channel first so that nobody else steals it while we're reading it.

In `crossbeam-channel`, only the zero-capacity flavor is implemented using one big mutex in front of the underlying data structure. But even in that case we have ugly complications. For example, in zero-capacity channels senders can either "offer" or "promise" a message. If a message is promised, then the sender will supply it only if some receiver actually comes and requests it. If we want to support requesting a reference to the message without commiting to it, the protocol will become incredibly complicated. :) And even then, that'd work with zero-capacity channels only. To make the operation work with other flavors we'd have to completely redesign the data structures and hurt performance.

May I ask why you need this operation? Do you need it for zero-capacity channels only? I'm trying to understand more about your problem. Perhaps we can find some other way around it. Or maybe build a slightly different synchronization primitive for your use case.

**Comment by droundy** [comment]
I've been thinking about designing a raft implementation in which messages are passed via channels, where the channels would serve as the API.  There are two semantics for sending a message that could be implemented, one would return immediately, and then the message would be sent when its able.  The other would return only when the message has been committed.  The latter would be impossible to implement purely via a "send" channel, and I was thinking that if the raft thread (which agrees on consensus) were to peek at the message, then send it, and only accept it once it has been committed, then the user of my API could specify which approach they wanted by deciding which kind of channel they used.

Without a "peek" feature, I would simply avoid exposing a channel to do sending, and implement a couple of methods for that, which might use private channels under the hood.  But I am intrigued by the idea of making channels be the only means of communication.

Another approach would be simply to have no synchronous send available, and tell users that they have to wait until they receive the committed message on the receive channel in order to act.  I think this is usually a better design, but it could complicate client code in some cases.  And it would seem a bit sad to hard-code into my API this restriction.

Now that I think about it, all I really need for this use case would be for the zero-sized channel to be handled, and really all I would need would be to delay the continuation of the sender until the receive was "finished", where "finished" is defined by the user of the Receiver.  One could do this either by calling a function, or by returning some kind of a guard type, which "finishes" the recv when it is dropped.

**Comment by stjepang** [comment]
Could you perhaps make it a rule that two messages must be sent into the channel instead of just one? So the first one is the actual message you want to send and the second one is just a blank *finish* message.

The sender would first send the actual message and then a *finish* message after it.
The receiver would receive the first message, do some work to process it, and finally receive the *finish* message.

**Comment by droundy** [comment]
That does seem like a pretty simple approach, albeit very user-visible.  It would cause a lag however, if there are multiple threads sending messages, since we couldn't read the second message from the channel (lest we read the "finish" message) until the first message was committed.  Of course, now I see that my own approach has precisely the same flaw.  It's just easier to see flaws in other people's suggestions!  :)

I think I'm convinced that this idea won't work for my use case, and so am closing the issue.  Thank you @stjepang for your helpful discussion!

**Comment by Thomasdezeeuw** [comment]
I've also had the need for `peek` method, but understand it is not possible to return a reference. But would it be possible to clone the message?

Something like this?
```rust
impl Receiver<T> {
    /// Peek a message.
    ///
    /// The next call to `peek`, `recv` and `try_recv` all return the same value.
    pub fn peek(&mut self) -> Option<T> where T: Clone {
        // ...
    }
}
```

**Comment by stjepang** [comment]
@Thomasdezeeuw 

While we're calling `peek` to clone an element, another thread might concurrently execute a `recv` operation and take ownership of that element. That means the `recv` operations must wait for `peek` to finish first.

So `peek` would first lock the tail of the queue, clone the last element, and then unlock the tail. It's a little bit complicated solution (and not a particularly fast one), but I think we could implement that. I'm still not sure it's worth it, though.

**Comment by Thomasdezeeuw** [comment]
We you say "lock the tail of the queue", does that mean locking receiving from the channel, locking sending to the channel, or both?

In my use case I only have a single receiver (mpsc), so only locking the receivers won't be a problem for me.

**Comment by stjepang** [comment]
That would mean internally locking the receiving end of the channel while the call to `.clone()` is executing.

By the way, could you perhaps describe what's your use case for the `peek` method?

**Comment by Thomasdezeeuw** [comment]
My use case is very simple, using the actor model I use crossbeam channels for message passing. Currently when an actor receives a message it removes it from the queue, but I want to be able to peek messages to ensure handling. So an actor can peek (clone) a message from the queue and in case it crashes the actor can be restarted and the message won't be lost.
