### ISSUE TITLE
Terminating / breaking select_loop

### ISSUE THREAD

**Issue by dbrgn** [crossbeam-rs/crossbeam-channel#27]
I may have missed a part of the docs, but is it possible to break/terminate a `select_loop`?

As an example, I have a thread that reads from stdin and pushes the line through a channel. On the other side, I read from that channel:

```rust
select_loop! {
  recv(stdin_rx, input) => {
    match &*input.trim() {
      ...
      "q" | "quit" => {
        println!("Goodbye");
        // break
      },
      ...
    }
  },
  ...
}
```

Is this conditional "break" possible somehow?

**Comment by dbrgn** [comment]
Oh, I think I misunderstood the `select_loop` macro (should have tried it first). Am I right that `select_loop` will only wait until one condition matches, and will then terminate (similar to `Select` that may only be used once)? Might it be a good idea to rename the macro to `select!`?

**Comment by stjepang** [comment]
> Am I right that `select_loop` will only wait until one condition matches, and will then terminate (similar to `Select` that may only be used once)? Might it be a good idea to rename the macro to `select!`?

Yes, as soon as one condition matches, the loop terminates.

The reason why the macro is named `select_loop!` rather than `select!` is that it makes you aware that it internally runs a loop. For example, if you write the following, `get_receiver()` might be called multiple times, and that fact should stand out:

```rust
select_loop! {
    recv(get_receiver(), _) => {
        // ...
    }
}
```

However... I believe there is a way to get rid of the internal loop and call `get_receiver()` only once. When/if we do that, it'll be completely reasonable to rename the macro to `select!`.

**Comment by dbrgn** [comment]
I see :) I'll try to come up with a small docs improvement PR.

**Comment by dbrgn** [comment]
Oh, never mind, it's already there...

> The macro is in fact loop, which is continuously probing both channels until one of the cases successfully receives a message. Then we print the message and the loop is broken.

I must have missed that when I read the docs. Sorry, my bad!
