### ISSUE TITLE
More flexible iterator recv() form in select?

### ISSUE THREAD

**Issue by birkenfeld** [crossbeam-rs/crossbeam-channel#50]
My situation is that I have a vector of "client" structures, each of which has a channel.

In version 0.1, I had a manual `Select` loop with the following:
```
                for mut client in &mut clients {
                    if let Ok(msg) = select.recv(&client.chan) {
                        /* process msg here, which uses `client` mutably */
```
That is, I need a mutable reference to the containing struct inside the handling code.

With the new select, there is a nice way to use an iterator over receivers, but I can't build that in a way that would allow me the mutable access to `client`.

I see two ways to make this possible:

* Add a form that in addition to the iterator, also passes a closure that retrieves an actual channel from the iterator items, but pass the iterator item, not the channel, as `from`.

* Make the trait for the first argument to `recv` public, so that I could implement it for `Client`, or add a trait for the items of the iterator.

Is there anything else?

**Comment by stjepang** [comment]
Would something like this work for you?

```rust
let (msg, i) = select! {
    recv(
        clients.iter().map(|c| &c.chan),
        msg,
        from,
    ) => {
        let i = clients.iter()
            .enumerate()
            .find(|(_, c)| &c.chan == from)
            .unwrap()
            .0;
        (msg, i)
    }
};
let client = &mut clients[i];
```

Hopefully this becomes a little bit easier once we get NLL.

**Comment by birkenfeld** [comment]
It would work, but would be even uglier than that, since the select also has other cases, one of which is another such vector.

I also don't like the extra loop over the vector, which is not particularly efficient (and which would remain even with NLL).

**Comment by stjepang** [comment]
> I also don't like the extra loop over the vector, which is not particularly efficient (and which would remain even with NLL).

This shouldn't be a concern. The `select!` macro already does the following, at the very least:

1. Iterates over the vector, and fills a `SmallVec` with receivers.
2. Randomly shuffles the `SmallVec`.
3. Iterates over the `SmallVec` in an attempt to execute receive operations.

One extra pass that compares channel addresses should comparatively take a negligible amount of time.

Rather than adding extra syntax to `select!`, I'm hoping the following becomes possible, assuming we get NLL and add `index_of` to `Itertools`:

```rust
let chans = clients.iter().map(|c| &c.chan);
select! {
    recv(chans, msg, from) => {
        let index = chans.index_of(from);
        let client = &mut clients[index];
        // ...
    }
}
```

This isn't too bad, but I'll give it some more thought.

**Comment by birkenfeld** [comment]
Thanks for considering. (Having a trait for "something you can get a receiver from" would not require new syntax.)

**Comment by birkenfeld** [comment]
I just tried the suggested replacement, and it fails because `clients` is also borrowed mutably in another arm of the `select`... even `#[feature(nll)]` doesn't seem to allow something like this:
```
select! {
    recv(x, y) => channels.push(y),
    recv(&channels, y, from) => ...
}
```

All in all, this makes it pretty unattractive for me to update to 0.2.

**Comment by stjepang** [comment]
I can confirm that it doesn't work with even with `#![feature(nll)]`. PR #60 will fix that.

**Comment by birkenfeld** [comment]
Thanks, that helps! Still think that the trait would be a good way to handle this more nicely :smiling_imp:

**Comment by stjepang** [comment]
The solution suggested in [this comment](https://github.com/crossbeam-rs/crossbeam-channel/issues/50#issuecomment-396567185) is the way to go (as soon as we get NLL). And the cost of iteration is really negligible so that shouldn't be something to worry about.

Sorry if this is not the solution you were hoping for, but I don't think it's much worse than exposing the `RecvArgument` trait. Thanks for the discussion - this was really helpful! If you have any other thoughts or comments, let me know. :)

Closing.

**Comment by birkenfeld** [comment]
Or use Select from https://github.com/crossbeam-rs/crossbeam-channel/pull/86?

**Comment by stjepang** [comment]
So `select!` accepts a static list of cases, while `Select` can add cases dynamically at the cost of being somewhat slower and more restrictive with respect to borrow checking.

I don't think `Select` will be useful in this situation.
