### ISSUE TITLE
Specify used go/rust version in benchmarks

### ISSUE THREAD

**Issue by cynecx** [crossbeam-rs/crossbeam-channel#71]
It's not clear what version of go or rust has been used to produce the sample benchmark :)

Also it seems that Go (`go1.10.3 linux/amd64`) is _slightly_ ahead of crossbeam-channel (bounded channel) ;)
![plot](https://user-images.githubusercontent.com/5961244/42470642-62652ec2-83bb-11e8-912a-17de43a255a1.png)

System: `Linux 4.17.5-1-ARCH #1 SMP PREEMPT`
CPU: `Intel(R) Core(TM) i7-6700K CPU` (4 physical cores/8 logical cores)
Go: `go1.10.3 linux/amd64`
Rust: `rustc 1.29.0-nightly (960f6046c 2018-07-08)`

**Comment by stjepang** [comment]
Ok, I've upgraded Go and reran benchmarks.

System: `Linux 4.16.13-200.fc27.x86_64 #1 SMP`
CPU: `Intel(R) Core(TM) i7-5600U CPU` (2 physical cores/4 logical cores)
Go: `go1.10.3 linux/amd64`
Rust: `rustc 1.29.0-nightly (960f6046c 2018-07-08)`

These are my results:

![plot](https://i.imgur.com/2bibgSR.png)

I wonder why Go is faster on your machine when capacity=0. Perhaps the backoff strategy has to be tweaked a little....

If you could do me a favor, open `src/internal/utils.rs` and find the following piece of code:

```rust
        if self.0 <= 6 {
            for _ in 0..1 << self.0 {
                atomic::spin_loop_hint();
            }
            self.0 += 1;
            true
        } else if self.0 <= 10 {
            thread::yield_now();
            self.0 += 1;
            true
        } else {
            thread::yield_now();
            false
        }
```

Try changing numbers `6` and `10` (bump them up or down, whatever works better) and run the benchmark for `crossbeam-channel`:

```
cd benchmarks
cargo run --release --bin crossbeam-channel
```

Maybe that'll improve results on your machine. Let me know if that helps. :)

**Comment by cynecx** [comment]
@stjepang I've tried several values (4, 8; 8,12; 16, 20; 16, 30; ...) without much difference in performance, it stays mostly +/- ~0.030 sec (for bounded0_*)

**Comment by stjepang** [comment]
Thanks! That's interesting. I'm still convinced that thread synchronization just needs some tuning since in those tests threads basically ping-pong each other all the time and there is no message buffering in the channels anyway.

I'll get a machine more similar to yours and see if the numbers can be improved.

**Comment by stjepang** [comment]
Ok, I did some benchmarking on a more beefy Intel machine and can confirm that Go is indeed faster when capacity=0 or capacity=1. The yielding strategy seems to affect the times a lot, but I couldn't tweak it to give much better results.

It seems the reason for that is simply that context switching between OS threads (and thread notification, too) is more expensive than context switching between goroutines. Therefore, those benchmarks are essentially measuring the cost of context switching rather than the cost of sending messages through channels.

We might be able to beat Go when crossbeam-channel gets futures support... we'll see.
