### ISSUE TITLE
Optimize bare send in select

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#94]
We should optimize these cases by calling dedicated functions instead of going through the full selection procedure:

```rust
select! {
   send(s, msg) => body
}
```

```rust
select! {
   send(s, msg) => body1,
   default => body2,
}
```

**Comment by kleimkuhler** [comment]
I'll work on this. I'll reference to a feature branch when I have some working changes.

**Comment by stjepang** [comment]
This looks pretty good -- you're on the right track.

So the problem is that in the optimized non-blocking send we'll evaluate `msg` and move it into the call to `send_nonblocking`. Then we check whether the message was sent or the channel was full.

We'll need to make non-blocking send a two-step process instead. We must evaluate `msg` after checking whether the message can be sent:

```rust
if $handles.len() == 1 {
    let mut token = Token::default();
    let res = $crate::internal::channel::send_nonblocking($handles[0].0, &mut token);

    match res {
        $crate::internal::channel::SendNonblocking::Full => {
            drop($handles);
            $default_body
        }
        $crate::internal::channel::SendNonblocking::Sent => {
            let $s = {
                // We have to prefix variables with an underscore to get rid of warnings when
                // evaluation of `$m` doesn't finish.
                let _s = $handles[0].0;
                let _guard = $crate::internal::utils::AbortGuard(
                    "a send case triggered a panic while evaluating its message"
                );
                let _msg = $m;

                #[allow(unreachable_code)]
                {
                    ::std::mem::forget(_guard);
                    #[allow(unsafe_code)]
                    unsafe { $crate::internal::channel::write(_s, &mut token, _msg); }
                    _s
                }
            };
            drop($handles);
            $send_body
        }
    }
} else {
    // ...
}
```

Now function `send_nonblocking` only takes the sender and the token as parameters. In it, we just need to match on the channel flavor and call `chan.sender().try(token)`. If that returns `true`, the send can proceed with evaluation of `$m` and a call to `write`, and if it returns `false`, the channel is full.

**Comment by kleimkuhler** [comment]
That makes sense. I realized that `let msg = $m` is probably not helping at all because it still `move`s the value since `T` does not necessarily implement `Clone` (correct me if that logic is wrong!)

Thank you for pointing out `Token` that helps out a lot. I saw that `fn write` was being used directly in the non-optimized `send`, but I was sure why exactly it _knew_ it could write. It makes sense now that `token` holds the information required to do so.

I'll make these changes and get a PR in!

@stjepang  quick note: I do not get any compiler warnings when I drop the `_` before variable names when evaluating `$m`. That may be a lint that used to give you warnings, but it doesn't seem to now. Would you still like me to keep that practice?

**Comment by stjepang** [comment]
Let's keep the underscores. Otherwise, warnings inside the macro codegen will appear if you write this:

```rust
select! {
    send(s, unreachable!()) => {}
}
```
